apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: 11124githubjenkinsdotnet
  janus-idp.io/tekton: 11124githubjenkinsdotnet
  backstage.io/kubernetes-id: 11124githubjenkinsdotnet
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: 11124githubjenkinsdotnet
resources:
- deployment.yaml
- route.yaml
- service.yaml
