apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: 11124githubjenkinsdotnet
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 11124githubjenkinsdotnet 
  name: 11124githubjenkinsdotnet
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: 11124githubjenkinsdotnet
    weight: 100 
