apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: 11124githubjenkinsdotnet
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 11124githubjenkinsdotnet 
  name: 11124githubjenkinsdotnet
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: 11124githubjenkinsdotnet 
